version: '1.0' #doesnt matter tbh.
services:
  backend:
    build: 
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      -"8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:mypassword@postgres:5432/postgres
    depends_on:
      - postgres
  ws:
    build: 
      context: .
      dockerfile: docker/Dockerfile.ws
    ports:
      -"8081:8081"
    environment:
      - DATABASE_URL=postgresql://postgres:mypassword@postgres:5432/postgres
    depends_on:
      - postgres
  frontend:
    build: 
      context: .
      dockerfile: docker/Dockerfile.frontend
      args:
        - DB_URL=postgresql://postgres:mypassword@postgres:5432/postgres
    ports:
      -"3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:mypassword@postgres:5432/postgres
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      -5432:5432
    environment:
      - POSTGRES_PASSWORD=mypassword
    volumes:
      -postgres_data:/var/lib/postgresql/DATABASE_URL
volumes:
  postgres_data: