FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./package*.json .

COPY ./bun.lock .

COPY ./turbo.json .

RUN bun i

COPY ./packages ./packages

COPY ./apps/backend ./apps/backend

RUN bun run generate:db

EXPOSE 8080

CMD [ "bun", "start:backend" ]