FROM oven/bun:1

WORKDIR /usr/src/app

ARG DB_URL

COPY ./packages ./packages

COPY ./apps/web ./apps/web

COPY ./package.json .

COPY ./bun.lock ./bun.lock

COPY ./turbo.json ./turbo.json

RUN bun i

RUN bun run generate:db

RUN DB_URL=${DB_URL} bun turbo run build

EXPOSE 3000

CMD [ "bun", "start:frontend" ]