name: Deploy backend
on:
  push: 
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning the code to github ubuntu machine.
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and then push it to dockerhub
        uses: docker/build-push-action@v4
        with: 
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/monorepo-with-ci-cd-and-docker-compose-backend:${{ github.sha }}